# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/en/stable/ci/index.html >

language: python
python:
    - "2.7"

sudo: false

install:
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      else
          if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi

script:
    - echo "Run tests on Travis.CI Linux machine"
    - cd tests
    - mkdir -p build
    - cd build
    - cmake ../
    - make
    - ./tests
